# Generated by Django 5.1.6 on 2025-02-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
    ]
