# Generated by Django 5.1.6 on 2025-02-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_writers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
