# Generated by Django 5.1.4 on 2025-03-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_person_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
